### PR TITLE
Fix source select not showing anime titles

### PR DESCRIPTION
**Pull request by joezito129**
Please check this fix out for Anime title and Episode Plot does not show during playback when using select source.

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Hey real quick before i merge, can you name some anime titles that were not working for source select?

**Comment by joezito129** [comment]
They all were not working.

**Comment by Goldenfreddy0703** [comment]
> They all were not working.

Weird, they were all working for me just fine, I will go ahead and merge and release then.

Thank you

**Comment by joezito129** [comment]
That is weird, when I used select source option to play any video it would not parse the title and plot info.
also i think i think other people where having this problem as it is listed on your todo list.

**Comment by Goldenfreddy0703** [comment]
> That is weird, when I used select source option to play any video it would not parse the title and plot info. also i think i think other people where having this problem as it is listed on your todo list.

Could probably either be due to a widget issue.

**Pull request merged**
