### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Pahiro**
Adding the CountryOfOrigin filter in for the upcoming season so my "Airing Anime Calendar" isn't flooded with Chinese and Korean animes releasing at the same time.

### CODE REVIEW

**Comment by Pahiro** [comment]
Let me remove the debugger reference

**Comment by Goldenfreddy0703** [comment]
Hey I see what you did and it's genius, I'm not a big fan of having Korean or Chinese anime in the calender and I did not know how to add country of origin with the anichart calender. Thank you very much for adding this. In a few hours I will make a release for this but again, thank you.

In the future, I may need your help with some filters if your available like content format and streaming site maybe for the calender someday. 

If you like feel free to contact me on discord or keybase and we can help improve Otaku more in the future.

**Comment by Goldenfreddy0703** [comment]
Hey, sorry i took forever to make a release but i tested your release today and it works like a charm. There is one small downside but its totally fine, when changing CountryOfOrigin filter, you have to either clear cache or rebuild in order for the "Airing Anime Calendar" to take affect. So far everything does work so thank you for adding this future, hopefully if we get in contact, we can add more features in the future. 

Thank you.

**Comment by Pahiro** [comment]
I'll look at solving that for you. Can probably check the Country flag when entering the calendar to compare to what's in memory and then do a full refresh on mismatch.

**Comment by Goldenfreddy0703** [comment]
> EDIT: Or actually, thinking about it, it's probably appropriate to refresh the cache whenever you leave the settings page

Actually, that maybe a good idea cause sometimes on kodi skins or when authenticating your debrid or watchlist, there are times where you would have to restart kodi in order to get your debrid or watchlist working. Maybe it would possibly be a good idea.

**Pull request merged**
