### PR TITLE
Update strings.po all languages 

### PR DESCRIPTION
**Pull request by icarok99**
Reason for change: it was breaking the translation

### CODE REVIEW

**Comment by icarok99** [comment]
@Ludovik35 @taiseer999 Do not translate this because translated causes problems in the addon.

msgctxt "#40370"
msgid "Romaji (Shingeki no Kyojin)"
msgstr ""

msgctxt "#40371"
msgid "English (Attack on Titan)"
msgstr ""

**Comment by Goldenfreddy0703** [comment]
Hey so I accidentally translated those cause I thought they needs translating, my bad.

About your pull, is there an alternative way to change them instead of deleting them? Reason why is cause these menu categorys have helped me understand which is what and it helps significantly especially when adding new settings to Otaku.

**Comment by icarok99** [comment]
> Hey so I accidentally translated those cause I thought they needs translating, my bad.
> 
> About your pull, is there an alternative way to change them instead of deleting them? Reason why is cause these menu categorys have helped me understand which is what and it helps significantly especially when adding new settings to Otaku.

I'll do some tests here

**Comment by Goldenfreddy0703** [comment]
Aww but then you would have to open the backup and all and stuff. 

Ok what if you used just one "#" not just a bunch cause that's probably what bugged it. 

So like for example:

# MAIN MENU DIRECTORY

Would this still break it?

**Comment by icarok99** [comment]
> Look at serens string file example, they do this.
> 
> Example 1 - "#: Text" Example 2 - "# Text"
> 
> https://github.com/nixgates/plugin.video.seren/blob/master/resources%2Flanguage%2Fresource.language.el_gr%2Fstrings.po

But seren's is for specify where the text is.

**Comment by icarok99** [comment]
IMG_20240122_123909
IMG_20240122_123921

**Comment by icarok99** [comment]
> @ludovik35 @taiseer999 Do not translate this because translated causes problems in the addon.
> 
> msgctxt "#40370" msgid "Romaji (Shingeki no Kyojin)" msgstr ""
> 
> msgctxt "#40371" msgid "English (Attack on Titan)" msgstr ""

Only with this removal it stopped breaking the translation.

**Comment by Goldenfreddy0703** [comment]
Aww that's too bad, ok well, let me do a little bit more research and if I can't find anything then I will merge and all.

**Comment by Goldenfreddy0703** [comment]
Hey @icarok99 , sorry I didn't merge yesterday but I plan to merge today, if you want, go ahead and remove those categories and maybe space them if possible and we can go ahead and merge.

**Comment by icarok99** [comment]
> Hey @icarok99 , sorry I didn't merge yesterday but I plan to merge today, if you want, go ahead and remove those categories and maybe space them if possible and we can go ahead and merge.

With the removal of the translation and correction in one of the translations, the translation stopped breaking. I will keep the categories.

**Comment by Goldenfreddy0703** [comment]
Oh that's great, ok awesome then I will merge in a few. Thanks

**Pull request merged**
