### PR TITLE
Fix for empty Kitsu lists

### PR DESCRIPTION
**Pull request by miguelkennedy**
If an empty list is encountered instead of erroring out we show an empty directory to the end user

Refer to issue https://github.com/Goldenfreddy0703/Otaku/issues/26

### CODE REVIEW

**Review by joezito129 — CHANGES_REQUESTED** [review]
the code you added should be above line 125 otherwise you will get a KeyError
el = result["included"][:len(_list)]

**Comment by Goldenfreddy0703** [comment]
> Thank you for spotting it... Should have double checked before pulling

Hey, that's ok. Whenever your pr is ready, pls tell me and i will merge your pr.

**Comment by miguelkennedy** [comment]
Done! :)

**Comment by Goldenfreddy0703** [comment]
Hey nice but from looking at it, your branch appears to have not been edited for 3 hrs. Was there anything that needed to be update by any chance?

**Comment by Goldenfreddy0703** [comment]
Ahh ok there we go, ready to merge lol

**Comment by Goldenfreddy0703** [comment]
Hey @miguelkennedy , by anychance, could you also do the same with Anilist and Mal?

**Comment by miguelkennedy** [comment]
@Goldenfreddy0703  looking into it... i'm testing them to see if they suffer from the same bug as Kitsu

**Comment by Goldenfreddy0703** [comment]
Actually its only Anilist that suffers the same bug, Mal is good.

**Comment by miguelkennedy** [comment]
Just tested both MAL and Anilist with newly created accounts and neither of them suffer from the same bug. I can navigate inside my empty lists and it correctly displays an empty folder without outputting any errors.

I don't know if the issue you're seeing might be platform or kodi version specific but for what it's worth on Kodi 19.4 | Apple TV 4K there are no issues with neither MAL or Anilist 👍🏼

**Comment by Goldenfreddy0703** [comment]
Oh....I guess it was just a Mal bug then 😅

Thank you very much for testing and for making a pr for this Mal bug, I think i might do a release today.

**Pull request merged**
