### PR TITLE
depreciated .setinfo()

### PR DESCRIPTION
**Pull request by joezito129**
I think the issue with the nextup widget has to do with this.
Please test and let me know if there are any errors and let me know if it fixes the nextup widget showing the correct plot.

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Heyyy sure, i will be glad to test this, thank you

**Comment by Goldenfreddy0703** [comment]
Ok so something interesting, some animes on my next up shows the series plots, whenever you click an anime, it plays the episode thats next up but when i back out, it will show the episode plot. 

Before playing the episode:
image

After playing the episode:
image

There is a possibility that you may have to get the consumet api to fetch all the episode meta for every anime in the next up in order to get the episode plot to show up.

**Comment by Goldenfreddy0703** [comment]
oh btw, the next up widget does not really have anything to do with it but i think the playlist could be which is why we have a branch for it, we just need to update it to work with the consumet api.

**Comment by Goldenfreddy0703** [comment]
Oh, one last thing, if you have keybase or discord, you should add me, we can talk alot more on there about your pr or the issues. 
Pls feel free to add me if you like to. 
## Contact

Discord: The Steampunk Owl#3126

Keybase: [Goldenfreddy0703](https://keybase.io/goldenfreddy0703)

**Comment by joezito129** [comment]
Yeah, I have discord. I just added you.

**Comment by Gujal00** [comment]
@joezito129 the setcast is still a problem in your code, I do have the full changes for this in my branch for a while now, but didnt merge to main. @Goldenfreddy0703 please hold off merging this as I already have the full code for the Kodi 20 setinfo changes

**Comment by Gujal00** [comment]
> Ok so something interesting, some animes on my next up shows the series plots, whenever you click an anime, it plays the episode thats next up but when i back out, it will show the episode plot.
> 
> There is a possibility that you may have to get the consumet api to fetch all the episode meta for every anime in the next up in order to get the episode plot to show up.

This is normal for currently airing anime and for older anime if you have never browsed it before.
The next up logic only looks for plot from the existing episode meta, so if the epidoe meta is not populate din the db by a prior action it wont show plot

**Comment by Goldenfreddy0703** [comment]
Hey @Gujal00 , sure i already reviewed this and found out that this was not ready to be merged.

**Comment by Goldenfreddy0703** [comment]
> This is normal for currently airing anime and for older anime if you have never browsed it before. The next up logic only looks for plot from the existing episode meta, so if the episode meta is not populated in the db by a prior action it wont show plot

Ahh ok makes sense. If by anychance, if we were to populate just the episodes for just the next up menu. How slow would you think it would be using this? 

`https://api.consumet.org/meta/anilist/episodes/{id}`

**Comment by Gujal00** [comment]
Yeah it is on my todo list. Also the MAL and Kitsu watchlist flavours need to updated as well to collect meta using consumet. Currently they dont. So yeah I will get on to cleaning up that code.

**Comment by Goldenfreddy0703** [comment]
> Yeah it is on my todo list. Also the MAL and Kitsu watchlist flavours need to updated as well to collect meta using consumet. Currently they dont. So yeah I will get on to cleaning up that code.

ahh ok thank you very much.

**Comment by joezito129** [comment]
Im going close this pr as GuaI00 already made a fix for this.

**Comment by Goldenfreddy0703** [comment]
Hey @joezito129 if you like, there is something i would like your help with but im not sure if its possible.

**Pull request closed without merging**
