### PR TITLE
Updated from Brazilian provider

### PR DESCRIPTION
**Pull request by icarok99**

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Hey there, thanks for providing a pr, did Otaku Animes change there website name?

**Comment by icarok99** [comment]
> Hey there, thanks for providing a pr, did Otaku Animes change there website name?

Yes

**Comment by icarok99** [comment]
Many anime sites are changing their name and URL to avoid being shut down

**Comment by Goldenfreddy0703** [comment]
Makes sense, will merge in a bit. Thanks

**Pull request merged**
