### PR TITLE
Request for a scraper timeout similar to other addons. #60

### PR DESCRIPTION
**Pull request by joezito129**
I added timeout setting for finding sources.

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Ok i tested your branch and im not going to lie, this is really cool and i like how you did. One thing i am going to do if you don't mind is setting the default to 10 instead of 30 sense 30 seconds takes forever. 

In the future i will improve on this and make it where if the user would like to have a scraper timeout or not. 

Again really love it and thank you.

**Comment by joezito129** [comment]
I was actually just thinking that 30 seconds seemed to long. 10 seconds sounds perfect.

**Comment by Goldenfreddy0703** [comment]
Again thank you very much, scrapping looks a lot cleaner with this setting and you can actually see the blocks loading when scrapping.

Thank you

**Comment by joezito129** [comment]
No problem, Glad I could help.

**Comment by Liquidrag** [comment]
Thank you @joezito129 and @Goldenfreddy0703 10 seconds is perfect.

**Pull request merged**
