### PR TITLE
New languages for addon (AR) (FR) (PT)

### PR DESCRIPTION
**Pull request by icarok99**
Credits for translation: @icarok99 @taiseer999 @Ludovik35

### CODE REVIEW

**Comment by icarok99** [comment]
All that remains is to edit the addon.xml

IMG_20240119_094537

**Comment by icarok99** [comment]
> > IMG_20240119_094537
> 
> Espere um pouco, o logotipo do Otaku sempre foi tão grande no arquivo de changelog, vou ter que dar uma olhada nisso para que caiba na página haha ​​🤣

It was big because of the image cropping

**Comment by icarok99** [comment]
> Ok it's been way too long, you already got a nice changelog ready and you fix some of our past mistakes so thank you.
> 
> I'm gonna have @Gujal00 review just to make sure then we can merge today, I'm still not familiar with strings yet cause I'm still wondering how you were able to convert every language in the strings file and I'm still wondering how I would add new settings to Otaku and if I need to edit all strings file and stuff. Hopefully I will be able to figure it out as a go but again, huge thank you for doing this.

And you won't need to create a setting to change the language because the language will be automatically recognized based on Kodi's language. 
Screenshot_2024-01-19-11-27-48-374_org xbmc kodi

**Comment by icarok99** [comment]
> Ok it's been way too long, you already got a nice changelog ready and you fix some of our past mistakes so thank you.
> 
> I'm gonna have @Gujal00 review just to make sure then we can merge today, I'm still not familiar with strings yet cause I'm still wondering how you were able to convert every language in the strings file and I'm still wondering how I would add new settings to Otaku and if I need to edit all strings file and stuff. Hopefully I will be able to figure it out as a go but again, huge thank you for doing this.

When you add new settings, the language of the added setting will be in English until the person translates it into their language.

**Comment by Goldenfreddy0703** [comment]
> When you add new settings, the language of the added setting will be in English until the person translates it into their language.

Ok that makes sense now, translating it will be hard unless there is a converter for it.

**Comment by icarok99** [comment]
> > When you add new settings, the language of the added setting will be in English until the person translates it into their language.
> 
> Ok that makes sense now, translating it will be hard unless there is a converter for it. Thank you

There are people who use poedit to edit without having to convert.

**Comment by Goldenfreddy0703** [comment]
Hey @icarok99 good news, i reviewed your pr and merged. You have all the settings translated but you forgot to update a label on the resource.language.pt_br folder so i went ahead and did that for you. We should be able to release tonight hopefully once i figure out how to merge mine and your commits into one.
https://github.com/Goldenfreddy0703/Otaku/commit/1a8d66e11bd953f99ae0d0a155af5c61ead68f8d

Thank you.

**Comment by icarok99** [comment]
> Hey @icarok99 good news, i reviewed your pr and merged. You have all the settings translated but you forgot to update a label on the resource.language.pt_br folder so i went ahead and did that for you. We should be able to release tonight hopefully once i figure out how to merge mine and your commits into one. [1a8d66e](https://github.com/Goldenfreddy0703/Otaku/commit/1a8d66e11bd953f99ae0d0a155af5c61ead68f8d)
> 
> Thank you.

I didn't translate because I was going to get the translation from the English language.

**Comment by icarok99** [comment]
https://github.com/elgatito/plugin.video.elementum/tree/master/scripts

https://github.com/elgatito/plugin.video.elementum/blob/master/resources/language/messages.pot

**Comment by icarok99** [comment]
Elgatito uses script to add things in all languages.

**Comment by Goldenfreddy0703** [comment]
oh thats interesting, thanks, btw i made a release so we should be all good

**Comment by Goldenfreddy0703** [comment]
> I didn't translate because I was going to get the translation from the English language.

wait, small question was it okay to merge and release?

**Pull request merged**
