### PR TITLE
Fix gogo and animix not working for several regions

### PR DESCRIPTION
**Pull request by piskndar**
Need to remind that animix server are **under maintenance** recently (19/12/2023).

### CODE REVIEW

**Comment by piskndar** [comment]
But aniwave, aniwatch and animepahe are not working for my region in Malaysia. I have no idea to fix.

**Comment by Goldenfreddy0703** [comment]
Hey there, thank you very much for making a pr on this. Today I'm sick but I will have @Gujal00 review this and hopefully will have time to make a quick release tonight or this afternoon.

Thank you

**Comment by Goldenfreddy0703** [comment]
> But aniwave, aniwatch and animepahe are not working for my region in Malaysia. I have no idea to fix.

Odd would it have something todo with your isp by anychance? My guess would probably be an isp thing but to test, if you have mobile data, connecting to the sites first on mobile data and then try connecting to the sites on your wifi and see if it's just your wifi. Thats my best guess.

**Comment by piskndar** [comment]
> Hey there, thank you very much for making a pr on this. Today I'm sick but I will have @Gujal00 review this and hopefully will have time to make a quick release tonight or this afternoon.
> 
> Thank you



> Hey there, thank you very much for making a pr on this. Today I'm sick but I will have @Gujal00 review this and hopefully will have time to make a quick release tonight or this afternoon.
> 
> Thank you

Your welcome. Hopefully your are in a good condition one day. By the way, I just changed their link. The link was safe and those are official mirror link for gogo and animix. [gogoanime](https://gogoanime3.net/) are not pass with several region but [Anitaku](https://anitaku.to/) (official mirror link) do the pass. But animix , I haven't be confirm the problem.

**Comment by piskndar** [comment]
> > But aniwave, aniwatch and animepahe are not working for my region in Malaysia. I have no idea to fix.
> 
> Odd would it have something todo with your isp by anychance? My guess would probably be an isp thing but to test, if you have mobile data, connecting to the sites first on mobile data and then try connecting to the sites on your wifi and see if it's just your wifi. Thats my best guess.

I've try them. Still on the problem. I guess it's a region problem

**Comment by Gujal00** [comment]
This should have been setup the way we did nyaa with alternate option, rather than changing the domain flatout. Now we may have broken for other regions who cannot access these new domains

**Comment by Goldenfreddy0703** [comment]
> This should have been setup the way we did nyaa with alternate option, rather than changing the domain flatout. Now we may have broken for other regions who cannot access these new domains

Hey @Gujal00, that's what I was thinking and that was my bad for merging early. Luckily I did not release today, It's still v51 so we should be good to either revert or change it.

**Pull request merged**
